[package]
name = "pyo3_mem_leak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
numpy = "0.21.0"
pyo3 = "0.21.2"
